
version: 2.1

defaults: &defaults
  working_directory: /go/src/github.com/getmilly/levels
  docker:
    - image: circleci/golang:1.11
commands:
  autotag:
    steps:
      - run: |
          make install-autotag
jobs:
  run-tests:
    <<: *defaults
    docker:
    - image: circleci/golang:1.11
    - image: nats-streaming
    - image: mongo
    steps:
      - checkout
      - run:
          name: Run Rebase
          command: make run-rebase
      - run:
          name: Install dep
          command: make install-dep
      - run:
          name: Build Package
          command: make build-package
      - run:
          environment:
            NATS_URL: nats://localhost:4222
            NATS_CLUSTER: test-cluster
            MONGO_URL: mongodb://localhost:27017
          name: Run Tests
          command: make run-tests
workflows:
  version: 2
  build-deploy:
    jobs:
      - run-tests